version: "3.9"

services:
  user-service:
    build: .
    container_name: user-service
    ports:
      - "4001:4001"
    environment:
      MONGO_URI: "mongodb+srv://ehakmath_db_user:XiTDdPqcVQfCMare@cluster0.mn0drdj.mongodb.net/user_service?appName=Cluster0"
      JWT_SECRET: testsecret
      JWT_EXPIRES_IN: 12h
    restart: unless-stopped
    networks:
      - user-service-network

networks:
  user-service-network:
    driver: bridge
